apiVersion: v2
name: bigbang
version: 1.6.2
description: Big Bang is a declarative, continuous delivery tool for core DoD hardened and approved packages into a Kubernetes cluster.

type: application

keywords:
  - platform1
  - bigbang

home: https://p1.dso.mil/#/products/big-bang
sources:
  - https://repo1.dso.mil/platform-one/big-bang/bigbang

maintainers:
  - name: Tom Runyon
    email: tom@runyon.dev
  - name: Josh Wolf
    email: josh@rancherfederal.com

icon: https://p1.dso.mil/img/Big_Bang_Color_Logo_White_text.b04263b1.png
