apiVersion: v2
name: kiali-operator
description: Kiali is an open source project for service mesh observability, refer to https://www.kiali.io for details.
version: 1.51.0-bb.3
appVersion: 1.51.0
home: https://github.com/kiali/kiali-operator
maintainers:
- name: Kiali
  email: kiali-users@googlegroups.com
  url: https://kiali.io
keywords:
- istio
- kiali
- operator
sources:
- https://github.com/kiali/kiali
- https://github.com/kiali/kiali-operator
- https://github.com/kiali/helm-charts
icon: https://raw.githubusercontent.com/kiali/kiali.io/master/themes/kiali/static/img/kiali_logo_masthead.png

dependencies:
  - name: gluon
    version: "0.2.10"
    repository: "oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon"
annotations:
  bigbang.dev/applicationVersions: |
    - Kiali: v1.51.0
