apiVersion: v2
name: bigbang
version: 2.14.0
description: Big Bang is a declarative, continuous delivery tool for core DoD hardened and approved packages into a Kubernetes cluster.

type: application

keywords:
  - platform1
  - bigbang

home: https://p1.dso.mil/products/big-bang
sources:
  - https://repo1.dso.mil/big-bang/bigbang

maintainers:
  - name: Ryan Garcia
    email: ryan.garcia@sigmadefense.com
  - name: Chris O'Connell
    email: coconnell@bridgephase.com

icon: https://p1.dso.mil/img/Big_Bang_Color_Logo_White_text.b04263b1.png
