{{- if or .Values.eckoperator.enabled .Values.logging.enabled .Values.clusterAuditor.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.eckoperator "name" "eck-operator" "defaults" (include "bigbang.defaults.eck-operator" .)) }}
{{- end }}

{{- define "bigbang.defaults.eck-operator" -}}
license:
  trial: {{ .Values.logging.license.trial }}
  keyJSON: |
    {{ .Values.logging.license.keyJSON | nindent 4 }}

image:
  pullPolicy: {{ .Values.imagePullPolicy }}
  
podAnnotations:
{{- if .Values.istio.enabled }}
  {{ include "istioAnnotation" . }}
{{- end }}

openshift: {{ .Values.openshift }}

istio:
  enabled: {{ .Values.istio.enabled }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

imagePullSecrets:
  - name: private-registry
{{- end -}}
