{{- $fluxSettingsGatekeeper := merge .Values.gatekeeper.flux .Values.flux -}}
{{- if or .Values.gatekeeper.enabled .Values.clusterAuditor.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gatekeeper
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: gatekeeper-system
  chart:
    spec:
      chart: {{ .Values.gatekeeper.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: gatekeeper
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsGatekeeper | nindent 2 }}

  {{- if .Values.gatekeeper.postRenderers }}
  postRenderers:
  {{ toYaml .Values.gatekeeper.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-gatekeeper-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-gatekeeper-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-gatekeeper-values
      kind: Secret
      valuesKey: "overlays"
{{- end }}
