{{- $fluxSettingsMinio := merge .Values.addons.minio.flux .Values.flux -}}
{{- if .Values.addons.minio.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/minio/values.yaml") . | sha256sum }}
spec:
  targetNamespace: minio
  {{- include "bigbang.helmRelease.chartSpec" (dict "name" "minio" "package" .Values.addons.minio "root" .) | nindent 2 }}

  {{- toYaml $fluxSettingsMinio | nindent 2 }}
  
  {{- if .Values.addons.minio.postRenderers }}
  postRenderers:
  {{ toYaml .Values.addons.minio.postRenderers | nindent 4 }}
  {{- end }}
  {{- include "bigbang.helmRelease.valuesFrom" (dict "name" "minio" "root" .) | nindent 2 }}

  dependsOn:
    {{- if .Values.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
    - name: minio-operator
      namespace: {{ .Release.Namespace }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}      
{{- end }}
