{{- $fluxSettingsNeuvector := merge .Values.neuvector.flux .Values.flux -}}
{{- if .Values.neuvector.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neuvector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: neuvector
    app.kubernetes.io/component: "sandbox"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/neuvector/values.yaml") . | sha256sum }}
spec:
  targetNamespace: neuvector
  chart:
    spec:
      {{- if eq .Values.neuvector.sourceType "git" }}
      chart: {{ .Values.neuvector.git.path }}
      sourceRef:
        kind: GitRepository
        name: neuvector
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ .Values.neuvector.helmRepo.chartName }}
      version: {{ .Values.neuvector.helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.neuvector.helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" .Values.neuvector.helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and .Values.neuvector.helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" .Values.neuvector.helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsNeuvector | nindent 2 }}

  {{- if .Values.neuvector.postRenderers }}
  postRenderers:
  {{ toYaml .Values.neuvector.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-neuvector-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-neuvector-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-neuvector-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.gatekeeper.enabled (include "istioEnabled" .) .Values.kyvernoPolicies.enabled .Values.monitoring.enabled }}
  dependsOn:
    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.istioCore.enabled }}
    - name: istio-core
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
