{{- $name := "disallow-deprecated-apis" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow Deprecated APIs
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: {{ default "low" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Kubernetes APIs
    policies.kyverno.io/description: >-
      Kubernetes APIs are sometimes deprecated and removed after a few releases.
      As a best practice, older API versions should be replaced with newer versions.
      This policy validates for APIs that are deprecated or scheduled for removal.
      Note that checking for some of these resources may require modifying the Kyverno
      ConfigMap to remove filters.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: validate-v1-22-removals
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    match:
      any:
      - resources:
          kinds:
          - admissionregistration.k8s.io/*/ValidatingWebhookConfiguration
          - admissionregistration.k8s.io/*/MutatingWebhookConfiguration
          - apiextensions.k8s.io/*/CustomResourceDefinition
          - apiregistration.k8s.io/*/APIService
          - authentication.k8s.io/*/TokenReview
          - authorization.k8s.io/*/SubjectAccessReview
          - authorization.k8s.io/*/LocalSubjectAccessReview
          - authorization.k8s.io/*/SelfSubjectAccessReview
          - certificates.k8s.io/*/CertificateSigningRequest
          - coordination.k8s.io/*/Lease
          - extensions/*/Ingress
          - networking.k8s.io/*/Ingress
          - networking.k8s.io/*/IngressClass
          - rbac.authorization.k8s.io/*/ClusterRole
          - rbac.authorization.k8s.io/*/ClusterRoleBinding
          - rbac.authorization.k8s.io/*/Role
          - rbac.authorization.k8s.io/*/RoleBinding
          - scheduling.k8s.io/*/PriorityClass
          - storage.k8s.io/*/CSIDriver
          - storage.k8s.io/*/CSINode
          - storage.k8s.io/*/StorageClass
          - storage.k8s.io/*/VolumeAttachment
    preconditions:
      all:
      {{- include "kyverno-policies.precondition.create-update-background" . | nindent 6 }}
      - key: "{{ "{{" }}request.object.apiVersion{{ "}}" }}"
        operator: AnyIn
        value:
        - admissionregistration.k8s.io/v1beta1
        - apiextensions.k8s.io/v1beta1
        - apiregistration.k8s.io/v1beta1
        - authentication.k8s.io/v1beta1
        - authorization.k8s.io/v1beta1
        - certificates.k8s.io/v1beta1
        - coordination.k8s.io/v1beta1
        - extensions/v1beta1
        - networking.k8s.io/v1beta1
        - rbac.authorization.k8s.io/v1beta1
        - scheduling.k8s.io/v1beta1
        - storage.k8s.io/v1beta1
    validate:
      message: >-
        {{ "{{" }} request.object.apiVersion {{ "}}" }}/{{ "{{" }} request.object.kind {{ "}}" }} is deprecated and will be removed in v1.22.
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
      deny: {{ "{}" }}
  - name: validate-v1-25-removals
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    match:
      any:
      - resources:
          kinds:
          - batch/*/CronJob
          - discovery.k8s.io/*/EndpointSlice
          - events.k8s.io/*/Event
          - autoscaling/*/HorizontalPodAutoscaler
          - policy/*/PodDisruptionBudget
          - policy/*/PodSecurityPolicy
          - node.k8s.io/*/RuntimeClass
    preconditions:
      all:
      {{- include "kyverno-policies.precondition.create-update-background" . | nindent 6 }}
      - key: "{{ "{{" }}request.object.apiVersion{{ "}}" }}"
        operator: AnyIn
        value:
        - batch/v1beta1
        - discovery.k8s.io/v1beta1
        - events.k8s.io/v1beta1
        - autoscaling/v2beta1
        - policy/v1beta1
        - node.k8s.io/v1beta1
    validate:
      message: >-
        {{ "{{" }} request.object.apiVersion {{ "}}" }}/{{ "{{" }} request.object.kind {{ "}}" }} is deprecated and will be removed in v1.25.
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
      deny: {{ "{}" }}
  - name: validate-v1-26-removals
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    match:
      any:
      - resources:
          kinds:
          - flowcontrol.apiserver.k8s.io/*/FlowSchema
          - flowcontrol.apiserver.k8s.io/*/PriorityLevelConfiguration
          - autoscaling/*/HorizontalPodAutoscaler
    preconditions:
      all:
      {{- include "kyverno-policies.precondition.create-update-background" . | nindent 6 }}
      - key: "{{ "{{" }}request.object.apiVersion{{ "}}" }}"
        operator: AnyIn
        value:
        - flowcontrol.apiserver.k8s.io/v1beta1
        - autoscaling/v2beta2
    validate:
      message: >-
        {{ "{{" }} request.object.apiVersion {{ "}}" }}/{{ "{{" }} request.object.kind {{ "}}" }} is deprecated and will be removed in v1.26.
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/
      deny: {{ "{}" }}
{{- end -}}