{{- $name := "disallow-istio-injection-bypass" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow Istio Injection Bypass
    policies.kyverno.io/category: Best Practices (Security)
    policies.kyverno.io/severity: {{ default "low" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pods
    policies.kyverno.io/description: >-
      The Istio service mesh uses a sidecar to encrypt traffic.  Unless an application is
      managing its own encrypted traffic, Istio should be used.  This policy validates
      that the pods do not have the sidecar.istio.io/inject label set to false.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: istio-on-pods
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    validate:
      message: >-
        The sidecar.istio.io/inject label cannot be false.
      pattern:
        metadata:
          =(labels):
            =(sidecar.istio.io/inject): "!false"
{{- end -}}