{{- $name := "disallow-rbac-on-default-serviceaccounts" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow RBAC on default Service Accounts
    policies.kyverno.io/category: Best Practices (Security)
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: RoleBinding,ClusterRoleBinding
    # More info: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions
    policies.kyverno.io/description: >-
      By default, pods are run using the automatically created `default` ServiceAccount in
      the pod's namespace.  The default service account has no permissions other than those
      of an unauthenticated user.  To enforce the least privilege best practice, additional
      permissions should not be allowed on the default service account.  This policy blocks
      role binding to default service accounts.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: validate-rbac-on-serviceaccount
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "RoleBinding" "ClusterRoleBinding")) .) | nindent 4 }}
    validate:
      message: "Adding permissions to the default service account is not allowed."
      pattern:
        =(subjects):
        - (kind): ServiceAccount
          name: "!default"
  - name: validate-rbac-on-group
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "RoleBinding" "ClusterRoleBinding")) .) | nindent 4 }}
    validate:
      message: "Adding permissions to a service account group is not allowed."
      pattern:
        =(subjects):
        - (kind): Group
          name: "!system:serviceaccounts*"
{{- end -}}