{{- $name := "disallow-namespaces" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow Default Namespace
    policies.kyverno.io/category: Best Practices (Security)
    policies.kyverno.io/severity: {{ default "low" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod, Deployment, StatefulSet, DaemonSet, Jobs, CronJobs
    policies.kyverno.io/description: >-
      Kubernetes Namespaces are an optional feature that provide a way to segment and
      isolate cluster resources across multiple applications and users. As a best
      practice, workloads should be isolated with Namespaces. Namespaces should be required
      and the default (empty) Namespace should not be used. This policy validates that resources
      specify a Namespace name other than `default`.
    # Pods will be deployed in same namespace as Pod controller if not specified in template
    pod-policies.kyverno.io/autogen-controllers: none
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: validate-namespace
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod" "Deployment" "StatefulSet" "DaemonSet" "Job" "CronJob")) .) | nindent 4 }}
    validate:
      message: "The namespace used for this resource is not allowed."
      pattern:
        metadata:
          namespace: "!{{ (dig $name "parameters" "disallow" nil .Values.policies) | join " & !" }}"
  {{- if has "default" (dig $name "parameters" "disallow" nil .Values.policies) }}
  - name: require-namespace
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod" "Deployment" "StatefulSet" "DaemonSet" "Job" "CronJob")) .) | nindent 4 }}
    validate:
      message: "A namespace is required."
      pattern:
        metadata:
          namespace: "?*"
  {{- end }}
{{- end -}}
