{{- $name := "disallow-pod-exec" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Disallow Pod Exec
    policies.kyverno.io/category: Best Practices (Security)
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/minversion: 1.4.2
    policies.kyverno.io/subject: PodExecOptions
    policies.kyverno.io/description: >-
      The `exec` and `attach` command may be used to gain shell access, or run other commands, in a
      container. While this can be useful for troubleshooting purposes, it could represent an attack
      vector and is discouraged.  This policy prevents pod exec and attach.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: disallow-exec
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "PodExecOptions" "PodAttachOptions")) .) | nindent 4 }}
    preconditions:
    - key: "{{ "{{" }}request.operation{{ "}}" }}"
      operator: Equals
      value: CONNECT
    validate:
      message: Cannot exec or attach to pods.
      deny: {}
{{- end -}}