{{- $name := "require-requests-equal-limits" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Resource Requests Equal Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.3.6
    policies.kyverno.io/description: >-
      Pods which have limits equal to requests are given a Guaranteed quality of service class
      which is the highest schedulable class. The Kubernetes scheduler assigns Guaranteed pods
      only to nodes which have enough resources to fulfil their CPU and memory requests.  In addition,
      Guaranteed pods are the last to be evicted when a node is running low on resources.  This policy
      checks that all containers have memory requests equal to limits to get a Guaranteed QoS class.
      This policy should only be assigned to critical resources.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  background: false
  rules:
  - name: require-requests-equal-limits
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    preconditions:
      all:
      - key: "{{"{{"}}request.operation{{"}}"}}"
        operator: In
        value:
        - CREATE
        - UPDATE
    validate:
      message: "CPU/memory requests must be equal to limits"
      foreach:
      # Resources are not allowed for ephemeral containers, but included here in case it changes
      - list: request.object.spec.[ephemeralContainers, initContainers, containers][]
        deny:
          conditions:
            any:
            - key: "{{ "{{" }} not_null(element.resources.requests.cpu, '') {{ "}}" }}"
              operator: Equals
              value: ""
            - key: "{{ "{{" }} not_null(element.resources.limits.cpu, '') {{ "}}" }}"
              operator: Equals
              value: ""
            - key: "{{ "{{" }} not_null(element.resources.requests.cpu, '') {{ "}}" }}"
              operator: NotEquals
              value: "{{ "{{" }} not_null(element.resources.limits.cpu, '') {{ "}}" }}"
            - key: "{{ "{{" }} not_null(element.resources.requests.memory, '') {{ "}}" }}"
              operator: Equals
              value: ""
            - key: "{{ "{{" }} not_null(element.resources.limits.memory, '') {{ "}}" }}"
              operator: Equals
              value: ""
            - key: "{{ "{{" }} not_null(element.resources.requests.memory, '') {{ "}}" }}"
              operator: NotEquals
              value: "{{ "{{" }} not_null(element.resources.limits.memory, '') {{ "}}" }}"
{{- end -}}