{{- $name := "require-istio-on-namespaces" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Require Istio Sidecar Injection on Namespace
    policies.kyverno.io/category: Best Practices (Security)
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/description: >-
      The Istio service mesh uses a sidecar to encrypt traffic.  Unless an application is
      managing its own encrypted traffic, Istio should be used.  This policy validates
      that the istio-injection label is set to enabled on namespace resources.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: istio-on-namespace
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Namespace")) .) | nindent 4 }}
    validate:
      message: "Namespaces must have `istio-injection: enabled` label."
      pattern:
        metadata:
          labels:
            istio-injection: "enabled"
{{- end -}}
