{{- $name := "require-labels" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Require Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: {{ default "low" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      A common set of labels on resources allows tools to work interoperably, describing objects
      in a common manner that all tools can understand and query.  This policy validates that
      the labels and values specified in the required list are present on pods.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: check-for-labels
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    validate:
      message: >-
        The pod is missing a required label.
      pattern:
        metadata:
          labels:
          {{- range $v := (dig $name "parameters" "require" nil .Values.policies) -}}
            {{- $t := split ":" $v }}
            {{- if $t._1 }}
              {{- $t._0 | nindent 12 }}: "{{ $t._1 | trim }}"
            {{- else }}
              {{- $t._0 | nindent 12 }}: "?*"
            {{- end }}
          {{- end }}
{{- end -}}