{{- $name := "restrict-capabilities" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Restrict Capabilities
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: {{ default "high" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access.
      Adding capabilities beyond the default set must not be allowed. This policy
      ensures users cannot add additional capabilities beyond the allowed list to a Pod.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: capabilities
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    validate:
      message: >-
        Adding of additional capabilities beyond the allowed set is not allowed.
        The fields spec.containers[*].securityContext.capabilities.add,
        spec.initContainers[*].securityContext.capabilities.add, and
        spec.ephemeralContainers[*].securityContext.capabilities.add must be in the allowed list.
      pattern:
        spec:
          containers:
            - =(securityContext):
                =(capabilities):
                  =(add): "{{ join " | " (dig $name "parameters" "allow" nil .Values.policies) }}"
          =(initContainers):
            - =(securityContext):
                =(capabilities):
                  =(add): "{{ join " | " (dig $name "parameters" "allow" nil .Values.policies) }}"
          =(ephemeralContainers):
            - =(securityContext):
                =(capabilities):
                  =(add): "{{ join " | " (dig $name "parameters" "allow" nil .Values.policies) }}"
{{- end -}}
