{{- $name := "restrict-host-ports" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Restrict Host Ports
    policies.kyverno.io/category: Pod Security Standards (Baseline)
    policies.kyverno.io/severity: {{ default "high" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Access to host ports allows potential snooping of network traffic and should not be
      allowed, or at minimum restricted to a known list. This policy ensures only approved ports
      are defined in container's `hostPort` field.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  rules:
  - name: host-ports
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    validate:
      message: >-
        The host port used is not allowed. The fields spec.containers[*].ports[*].hostPort,
        spec.initContainers[*].ports[*].hostPort, and spec.ephemeralContainers[*].ports[*].hostPort
        must only include ports from the allowed list.
      pattern:
        spec:
          =(initContainers):
            - =(ports):
              - =(hostPort): "{{ join " | " (dig $name "parameters" "allow" nil .Values.policies) }}"
          containers:
            - =(ports):
              - =(hostPort): "{{ join " | " (dig $name "parameters" "allow" nil .Values.policies) }}"
          # Ports are not allowed for ephemeral containers, but included here in case it changes
          =(ephemeralContainers):
            - =(ports):
              - =(hostPort): "{{ join " | " (dig $name "parameters" "allow" nil .Values.policies) }}"
{{- end -}}
