{{- $name := "restrict-volume-types" }}
{{- if and .Values.enabled (dig $name "enabled" false .Values.policies) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name }}
  annotations:
    policies.kyverno.io/title: Restrict Volume Types
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: {{ default "medium" (dig $name "severity" nil .Values.policies) }}
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Volume types, beyond the core set, should be restricted to limit exposure to potential vulnerabilities
      in Container Storage Interface (CSI) drivers.  In addition, HostPath volumes should not be allowed because
      host directories could be exploited to access shared data or escalate privileges.  This policy restricts
      use of volume types to the allowed list.
  labels: {{- include "kyverno-policies.labels" . | nindent 4 }}
spec:
  {{- include "kyverno-policies.webhookTimeoutSeconds" (merge (dict "name" $name) .) | indent 2 }}
  validationFailureAction: {{ default (dig $name "validationFailureAction" nil .Values.policies) .Values.validationFailureAction }}
  background: false
  rules:
  - name: restrict-volume-types
    {{- include "kyverno-policies.exclude" (merge (dict "name" $name) .) | indent 4 }}
    {{- include "kyverno-policies.match" (merge (dict "name" $name "kinds" (list "Pod")) .) | nindent 4 }}
    preconditions:
      all:
      - key: "{{"{{"}}request.operation{{"}}"}}"
        operator: In
        value:
        - CREATE
        - UPDATE
      - key: "{{"{{"}} not_null(request.object.spec.volumes[], '') | length(@) {{"}}"}}"
        operator: GreaterThanOrEquals
        value: 1
    validate:
      message: >-
        One or more volume types used in the pod is not in the allowed list.
      foreach:
      - list: "request.object.spec.volumes"
        anyPattern:
        {{- range $v := (dig $name "parameters" "allow" nil .Values.policies) }}
        - {{ $v }}: "*"
        {{- end }}
{{- end -}}