{{- /* Used for pulling images from custom registries.  One per namespace */ -}}
{{- if .Values.registryCredentials -}}
{{- range $ns := compact (splitList " " (include "uniqueNamespaces" (merge (dict "default" true) .))) -}}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: private-registry
    {{- include "commonLabels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" $ }}
---
{{- end -}}
{{- end -}}