{{- $pkg := "fortify" }}
{{- $fluxSettingsFortify := merge .Values.addons.fortify.flux .Values.flux -}}
{{- if (get .Values.addons $pkg).enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $pkg }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/fortify/values.yaml") . | sha256sum }}
spec:
  releaseName: {{ $pkg }}
  targetNamespace: {{ $pkg }}
  chart:
    spec:
      {{- if eq (get .Values.addons $pkg).sourceType "git" }}
      chart: {{ (get .Values.addons $pkg).git.path }}
      sourceRef:
        kind: GitRepository
        name: fortify
        namespace: {{ .Release.Namespace }}
      {{- else }}
      chart: {{ (get .Values.addons $pkg).helmRepo.chartName }}
      version: {{ (get .Values.addons $pkg).helmRepo.tag }}
      sourceRef:
        kind: HelmRepository
        name: {{ (get .Values.addons $pkg).helmRepo.repoName }}
        namespace: {{ .Release.Namespace }}
      {{- $repoType := include "getRepoType" (dict "repoName" (get .Values.addons $pkg).helmRepo.repoName "allRepos" $.Values.helmRepositories) -}}
      {{- if (and (get .Values.addons $pkg).helmRepo.cosignVerify (eq $repoType "oci")) }} # Needs to be an OCI repo
      verify:
        provider: cosign
        secretRef:
          name: {{ printf "%s-cosign-pub" (get .Values.addons $pkg).helmRepo.repoName }}
      {{- end }}
      {{- end }}
      interval: 5m

  {{- toYaml $fluxSettingsFortify | nindent 2 }}

  {{- if (get .Values.addons $pkg).postRenderers }}
  postRenderers:
  {{ toYaml (get .Values.addons $pkg).postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.istio.enabled .Values.kyvernoPolicies.enabled .Values.monitoring.enabled }}
  dependsOn:
    {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
