{{- if .Values.nexus.repository.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  creationTimestamp: null
  name: repo
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 90
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end }}
      containers:
      - image: "{{ .Values.job_image.repository }}:{{ .Values.job_image.tag }}"
        imagePullPolicy: {{ .Values.job_image.pullPolicy }}
        name: repo
        command:
          - sh
        args:
          - -c
          - |
            until curl --head localhost:15000; do echo "Waiting for Istio proxy sidecar"; sleep 10; done; echo "Sidecar available"  &&
            BASE_URL="http://{{ template "nexus.name" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.nexus.nexusPort }}"
            
            # repo creation
            {{- range .Values.nexus.repository.repo }}           
            STATUS=$(curl -X GET -s -o /dev/null -w '%{http_code}' \
                -u admin:"$API_CREDENTIALS" \
                "$BASE_URL/service/rest/v1/repositories/{{- .format }}/{{- .type }}/{{- .name }}" \
                -H "accept: application/json" \
                -H "Content-Type: application/json" \
            )
            if [ $STATUS -eq 200 ]
            then
              curl -X PUT \
                  -u admin:"$API_CREDENTIALS" \
                  "$BASE_URL/service/rest/v1/repositories/{{- .format }}/{{- .type }}/{{- .name }}" \
                  -H "accept: application/json" \
                  -H "Content-Type: application/json" \
                  -d {{ .repo_data | toJson | quote }}
            else
              curl -X POST \
                  -u admin:"$API_CREDENTIALS" \
                  "$BASE_URL/service/rest/v1/repositories/{{- .format }}/{{- .type }}" \
                  -H "accept: application/json" \
                  -H "Content-Type: application/json" \
                  -d {{ .repo_data | toJson | quote }}
            fi             
            {{- end }} 
            echo "Created repositories"
            
            curl -fsI -X POST http://localhost:15020/quitquitquit &&
            exit
        env:
        - name: API_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ template "nexus.name" . }}-secret
              key: admin.password
        resources: {}
      restartPolicy: Never
status: {}
{{- end }}