{{- if and .Values.sso.enabled .Values.secret.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  creationTimestamp: null
  name: saml
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 90
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end }}
      containers:
      - image: "{{ .Values.job_image.repository }}:{{ .Values.job_image.tag }}"
        imagePullPolicy: {{ .Values.job_image.pullPolicy }}
        name: saml
        command:
          - sh
        args:
          - -c
          - |
            until curl --head localhost:15000; do echo "Waiting for Istio proxy sidecar"; sleep 10; done; echo "Sidecar available"  &&
            BASE_URL="http://{{ template "nexus.name" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.nexus.nexusPort }}"
            # If there is a license key
            {{- if .Values.license_key }}
            # saml metadata
            curl -X PUT \
                 -u admin:"$API_CREDENTIALS" \
                 "$BASE_URL/service/rest/v1/security/saml" \
                 -H "accept: application/json" \
                 -H "Content-Type: application/json" \
                 -d "$IDP_DATA" &&
            # realm configuration
            curl -X PUT \
                 -u admin:"$API_CREDENTIALS" \
                 "$BASE_URL/service/rest/v1/security/realms/active" \
                 -H "accept: application/json" \
                 -H "Content-Type: application/json" \
                 -d "$REALM" &&
            {{- end }}
            # role creation
            {{- range .Values.sso.role }}
            curl -X POST \
                 -u admin:"$API_CREDENTIALS" \
                 "$BASE_URL/service/rest/v1/security/roles" \
                 -H "accept: application/json" \
                 -H "Content-Type: application/json" \
                 -d {{ . | toJson | quote }} &&
            {{- end }} 

            echo "Created roles"
            curl -fsI -X POST http://localhost:15020/quitquitquit &&
            exit
        
        env:
        - name: API_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: {{ template "nexus.name" . }}-secret
              key: admin.password
        - name: IDP_DATA
          valueFrom:
            configMapKeyRef:
              name: {{ template "nexus.name" . }}-sso
              key: idp-metadata
        - name: REALM
          valueFrom:
            configMapKeyRef:
              name: {{ template "nexus.name" . }}-sso
              key: realm
        - name: ROLE
          valueFrom:
            configMapKeyRef:
              name: {{ template "nexus.name" . }}-sso
              key: role
        resources: {}
      restartPolicy: Never
status: {}
{{- end }}