source: submodules/bigbang

ignore_patterns:
  - .gitignore
  - CODEOWNERS
  - oscal-component.yaml
  - renovate.json
  - "*.tgz"
  - "*.zip"
  - .gitlab-ci.yml
  - LICENSE
  - tests
  - .gitlab

nav:
  - ğŸ° Home: README.md
  - ğŸª™ Values: values.md
  - ğŸ“– Big Bang Docs: docs
  - ğŸ‘¥ Contributing: CONTRIBUTING.md
  - ğŸ“œ Changelog: CHANGELOG.md
  - ğŸ“¦ Package Overview: Packages.md
  # - ğŸ§­ Charter: charter