{{- if and (not .Values.offline) .Values.jaeger.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.jaeger.git.repo }}
  ref:
    {{- include "validRef" .Values.jaeger.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCreds" . | nindent 2 }}
{{- end }}
