{{- $fluxSettingsJaeger := merge .Values.jaeger.flux .Values.flux -}}
{{- if .Values.jaeger.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: jaeger
  chart:
    spec:
      chart: {{ .Values.jaeger.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsJaeger | nindent 2 }}

  valuesFrom:
    - name: {{ .Release.Name }}-jaeger-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-jaeger-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-jaeger-values
      kind: Secret
      valuesKey: "overlays"

  {{ if or .Values.istio.enabled .Values.monitoring.enabled .Values.jaeger.sso.enabled .Values.logging.enabled }}
  dependsOn:
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.jaeger.sso.enabled }}
    - name: authservice
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.logging.enabled }}
    - name: ek
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
