{{- $mmOpOldValues := default dict .Values.addons.mattermostoperator -}}
{{- $mmOpValues := mergeOverwrite $mmOpOldValues .Values.addons.mattermostOperator -}}
{{- $gitCredsSecretDict := dict
  "name" "mattermostOperator"
  "targetScope" $mmOpValues
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
