{{- $mmOpOldValues := default dict .Values.addons.mattermostoperator -}}
{{- $mmOpValues := mergeOverwrite $mmOpOldValues .Values.addons.mattermostOperator -}}
{{- if and (eq $mmOpValues.sourceType "git") (not .Values.offline) (or $mmOpValues.enabled .Values.addons.mattermost.enabled) }}
{{- include "bigbang.gitRepository" (dict "name" "mattermost-operator" "gitCredsName" "mattermostOperator" "git" $mmOpValues.git "component" "collaboration-tools" "root" .) }}
{{- end }}
