{{- if and (eq .Values.istioCNI.sourceType "git") (not .Values.offline) .Values.istioCNI.enabled }}
{{- include "bigbang.gitRepository" (dict "name" "istio-cni" "gitCredsName" "istioCNI" "git" .Values.istioCNI.git "component" "core" "root" .) }}
{{- end }}
